apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-hpa
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.hpaSpecs.maxReplicas }}
  minReplicas: {{ .Values.hpaSpecs.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName.model }}
  targetCPUUtilizationPercentage: {{ .Values.hpaSpecs.targetCPUUtilizationPercentage }}