apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.model }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ .Values.appName.model }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ .Values.appName.model }}
        spec:
            containers:
                - name: {{ .Values.appName.model }}
                  image: {{ .Values.image.modelServer }}
                  ports:
                      - containerPort: {{ .Values.port.modelServer }}