apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName.model }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app.kubernetes.io/name: {{ .Values.appName.model }}
    type: NodePort
    ports:
        - protocol: TCP
          port: {{ .Values.port.service }}
          targetPort: {{ .Values.port.modelServer }}